### ISSUE TITLE
Thanks a lot!

### ISSUE THREAD

**Issue by mwalid207** [Fabric-Development/fabric#22]
Thanks a lot , EWW is very hard but I know a some python so this is more beautifull!

[![ReadMeSupportPalestine](https://raw.githubusercontent.com/Safouene1/support-palestine-banner/master/banner-support.svg)](https://techforpalestine.org/learn-more)

**Comment by its-darsh** [comment]
you're welcome!, but it'd be better to use discussions instead of issues, i'm closing this _issue_ now
