### ISSUE TITLE
custom kbd name selection

### ISSUE THREAD

**Issue by Deeepkk** [Fabric-Development/fabric#3]
how to select custom keyboard name ?
I tried this `lang_instance_custom = Language(keyboard_name="at-translated-set-2-keyboard")
`
`DEBUG    | widgets:initlize_language:504 - [Language] Got language: English (US)
INFO     | widgets:initlize_language:512 - [Language] Set language: English (US) for keyboard: at-translated-set-2-keyboard
INFO     | widgets:on_ready:483 - [Language] Connected to the hyprland socket\
INFO     | widgets:initlize_language:512 - [Language] Set language: None for keyboard: usb-usb-keyboard`

got this which is correct but not showing in the bar. Also it is still checking for the **usb-usb-keyboard** specified in widgets.py.

**Comment by its-darsh** [comment]
so weird, i guess i have to revisit this class rn

**Comment by Deeepkk** [comment]
ah sorry, I forgot to add this
it originally dont check for usb-usb-kbd , it throws this message 
`Traceback (most recent call last):
  File "/home/deepak/temp/fabric-fork/fabric/hyprland/widgets.py", line 482, in on_ready
    self.initlize_language()
  File "/home/deepak/temp/fabric-fork/fabric/hyprland/widgets.py", line 513, in initlize_language
    f"[Language] Set language: {language} for keyboard: {self.keyboard_name}"
UnboundLocalError: cannot access local variable 'language' where it is not associated with a value`

I added language = None in widgets.py ( after line 495)
Sorry I added this to fix this error but forgot to mention it, after adding this the output is in first comment

**Comment by its-darsh** [comment]
@Deeepkk can you try the latest commit?

**Comment by Deeepkk** [comment]
` DEBUG    | widgets:initlize_language:506 - [Language] Got language: English (US)
INFO     | widgets:initlize_language:515 - [Language] Set language: English (US) for keyboard: at-translated-set-2-keyboard
 INFO     | widgets:on_ready:483 - [Language] Connected to the hyprland socket
 INFO     | widgets:initlize_language:519 - [Language] Could not find language for keyboard: usb-usb-keyboard, gotten keyboards: [{'address': '0x5e178246c500', 'name': 'power-button', 'rules': '', 'model': '', 'layout': 'us', 'variant': '', 'options': '', 'active_keymap': 'English (US)', 'main': False}, {'address': '0x5e17823c8ac0', 'name': 'video-bus', 'rules': '', 'model': '', 'layout': 'us', 'variant': '', 'options': '', 'active_keymap': 'English (US)', 'main': False}, {'address': '0x5e17824e4df0', 'name': 'power-button-1', 'rules': '', 'model': '', 'layout': 'us', 'variant': '', 'options': '', 'active_keymap': 'English (US)', 'main': False}, {'address': '0x5e1782560970', 'name': 'intel-hid-events', 'rules': '', 'model': '', 'layout': 'us', 'variant': '', 'options': '', 'active_keymap': 'English (US)', 'main': False}, {'address': '0x5e17825b0cb0', 'name': 'intel-hid-5-button-array', 'rules': '', 'model': '', 'layout': 'us', 'variant': '', 'options': '', 'active_keymap': 'English (US)', 'main': False}, {'address': '0x5e17825ea8b0', 'name': 'at-translated-set-2-keyboard', 'rules': '', 'model': '', 'layout': 'us', 'variant': '', 'options': '', 'active_keymap': 'English (US)', 'main': False}, {'address': '0x5e1782624c20', 'name': 'hp-wmi-hotkeys', 'rules': '', 'model': '', 'layout': 'us', 'variant': '', 'options': '', 'active_keymap': 'English (US)', 'main': True}]
INFO     | widgets:on_ready:483 - [Language] Connected to the hyprland socket`


Still nothing in bar

**Comment by its-darsh** [comment]
@Deeepkk this does not make any sense since if the return value of the keyboard init function is a logging statement (None), and the provided logs says

> INFO     | widgets:initlize_language:515 - [Language] Set language: English (US) for keyboard: at-translated-set-2-keyboard

means this widget got initialized with the string "English (US)" (if no there is no formatting using the FormatedString object)

and

> INFO     | widgets:initlize_language:519 - [Language] Could not find language for keyboard: usb-usb-keyboard

which's weird because the first log statement have been already done and the function returned

it looks like you have more than one widget (Language) instance, if so consider removing the unused one, also providing the config you're using will help alot

**Comment by Deeepkk** [comment]
I dont think I have more than one lang instance 
I am using examples/bar.py and added this line at 23
`lang_instance_custom = Language(keyboard_name="at-translated-set-2-keyboard")

**Comment by its-darsh** [comment]
> I dont think I have more than one lang instance I am using examples/bar.py and added this line at 23 `lang_instance_custom = Language(keyboard_name="at-translated-set-2-keyboard")

@Deeepkk i ran out of thoughts, what do you think might be causing this to happen?

**Comment by Deeepkk** [comment]
I am really sorry for wasting your time 😢 , you were correct there were two language instance. I added mine and forgot to check the one which was already in the example file.


`self.language = Language(
            keyboard_name="at-translated-set-2-keyboard",
            formatter=FormattedString(
                "{replace_lang(language)}",
                replace_lang=lambda x: bulk_replace(
                x,
                [r".*Eng.*", r".*Ar.*"],
                ["ENG", "ARA"],
                regex=True,
            ),
        ),
            name="hyprland-window",
        )`

**Comment by its-darsh** [comment]
@Deeepkk does it work fine now?

**Comment by Deeepkk** [comment]
Yes. You can close my dumb issue.
