### ISSUE TITLE
Commit Message Style

### ISSUE THREAD

**Issue by undonepotato** [Fabric-Development/fabric#36]
Does this repository use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)? The [docs](https://wiki.ffpy.org/code-style-guide.html) aren't very clear on this; they provide a format but don't mention the spec by name. Most commits in this repository seem to follow it, but not all. Clarity in the style guide in the docs would help, whether it does or not.

**Comment by undonepotato** [comment]
I also wasn't sure whether to put this in the wiki repo or this one but as it concerns this mostly I put it here. If there's a clear response, I'll probably try to edit the wiki.

**Comment by its-darsh** [comment]
in a nutshell, [read this](https://www.conventionalcommits.org)

**Comment by undonepotato** [comment]
So the answer is yes! I'll add a PR to the wiki clarifying this sometime.
