### ISSUE TITLE
PyPI and pip installation

### ISSUE THREAD

**Issue by undonepotato** [Fabric-Development/fabric#37]
Are there any plans in the future to add Fabric as a package on [PyPI](https://pypi.org)? This would simplify the process of installation tremendously.

(I realize this may be part of the rewrite, or if not, definitely a topic to discuss afterwards.)

**Comment by its-darsh** [comment]
it depends, we will use a build system later, which might be a pain to ship over PyPI, but installing from git ain't an issue (for now)

> (I realize this may be part of the rewrite, or if not, definitely a topic to discuss afterwards.)

we can address this later, followups on discord.
