### ISSUE TITLE
Layers not working properly on hyprland

### ISSUE THREAD

**Issue by Piker98988** [Fabric-Development/fabric#38]
Started working on the tutorial until when I ran the bar example script it appeared as a normal window instead of a layer. Tried the wiki's solution of setting the env var to wayland with only the `env GDK_BACKEND=wayland` part as for the `python path/to/fabric/config` I don't know what is the `path/to/fabric/config`. Thanks in advance!

Update 1:
Didn't know you could update. Searching console log found this:
https://pastebin.com/huFVzu0P

Update 2:
Ran it several times and got
`2024-07-20 19:53:10.068 | ERROR    | __main__:<module>:38 - Cvc is not installed, please install it first, you can use automated installer in the git repository
`
At least I know how to solve that by myself

Update 3:
Tried to reinstall fabric but won't stop throwing the `cloned/repository/path is not a clone of https://github.com/Fabric-Development/fabric`

**Comment by Piker98988** [comment]
Thought the problem may be waybar being installed and using the layer instead of fabric. I will try to uninstall waybar (If I manage to)

**Comment by Piker98988** [comment]
okay, managed to uninstall waybar and other widget apps but the problem persists. I'm going to try and execute it with verbose or something like that.

**Comment by Piker98988** [comment]
Okay... when executing the python file i got this:
`2024-07-20 19:55:01.605 | WARNING  | fabric.hyprland.service:event_socket_task:194 - got an unknown event from hyprland (['windowtitlev2', '627e8b1be1f0,MGMT - Little Dark Age']), probably a new event added to hyprland, report this.
2024-07-20 19:55:02.328 | WARNING  | fabric.hyprland.service:event_socket_task:194 - got an unknown event from hyprland (['windowtitlev2', '627e8b1e5700,Layers not working properly on hyprland · Issue #38 · Fabric-Development/fabric - Chromium']), probably a new event added to hyprland, report this.`
It says to report it, so don't know what to do.

**Comment by Axenide** [comment]
Hi, which distro are you on? If you are using Arch (btw) it is highly recommended to use the AUR package. Enable --devel when installing or updating fabric so you can get the latest commit.

I would like more details about your system so I can at least try to help you.

**Comment by Piker98988** [comment]
Yes, I'm on arch, what more would you need? Meanwhile, I will install the aur package

**Comment by Axenide** [comment]
> Yes, I'm on arch, what more would you need? Meanwhile, I will install the aur package

Your window manager and GPU would be a good start. :)

**Comment by Axenide** [comment]
Acabo de notar que hablas español, eso facilita las cosas.

**Comment by Piker98988** [comment]
Uso Hyprland y gráfica integrada radeon

**Comment by Piker98988** [comment]
En un portátil Ryzen 5 5500U gráficos integrados 512mib vram,  8GiB ram, 16GB swap, total nvme 512Gib

**Comment by Piker98988** [comment]
could this be an environment variable problem?

**Comment by Piker98988** [comment]
I did it. I solved it.
When this happens, you have to set the env variable `GDK_BACKEND` to `wayland` so fabric knows how to approach the layer system. the solution is, from wherever you're running your script, may it be the starter hyprland commands or a venv:
`export GDK_BACKEND=wayland`
and run it again. Thanks, @Axenide for the help!!
