### ISSUE TITLE
Fabric challenged on Debian

### ISSUE THREAD

**Issue by eirenicon** [Fabric-Development/fabric#46]
I am struggling to follow your tutorial without much success.  When I use your standard python commands, when fabric is installed in a an isolated fabric-venv directory they do not execute.

Here is the kind of error I get:

```
mark@debian ~/fabric-venv/fabric/lib/python3.12/site-packages
╰─➤  python test.py
Traceback (most recent call last):
  File "/home/mark/fabric-venv/fabric/lib/python3.12/site-packages/test.py", line 1, in <module>
    import fabric # importing the base packakge
    ^^^^^^^^^^^^^
  File "/home/mark/fabric-venv/fabric/lib/python3.12/site-packages/fabric/__init__.py", line 4, in <module>
    from fabric.client import get_fabric_dbus_proxy, get_dbus_client
  File "/home/mark/fabric-venv/fabric/lib/python3.12/site-packages/fabric/client.py", line 7, in <module>
    from fabric.service import *
  File "/home/mark/fabric-venv/fabric/lib/python3.12/site-packages/fabric/service.py", line 2, in <module>
    from fabric.utils import get_connectable_names_from_kwargs
  File "/home/mark/fabric-venv/fabric/lib/python3.12/site-packages/fabric/utils/__init__.py", line 1, in <module>
    from .helpers import *
  File "/home/mark/fabric-venv/fabric/lib/python3.12/site-packages/fabric/utils/helpers.py", line 11, in <module>
    gi.require_version("GtkLayerShell", "0.1")
  File "/home/mark/fabric-venv/fabric/lib/python3.12/site-packages/gi/__init__.py", line 122, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkLayerShell not available
╭─mark@debian ~/fabric-venv/fabric/lib/python3.12/site-packages
```

Any help is most appreciated. Sorry to be so dense.

**Comment by its-darsh** [comment]
Please use the new `rewrite` branch (#43) and read the new wiki's [installation guide](https://its-darsh.github.io/fabric-wiki/introduction/installation-guide/). from what I see in the provided error you seem not to have one of the required dependencies of Fabric (`gtk-layer-shell`).

**Comment by eirenicon** [comment]
Here's a shot of my gtk-shell installed items. From what I read, gtk-layer-shell-doc is the debian install of the arch gtk-layer-shell.  
![Screenshot_2024-10-22_06-54-58](https://github.com/user-attachments/assets/172f0693-367a-47a3-9b46-eed4b2c65576)

**Comment by its-darsh** [comment]
@eirenicon, You need to follow the provided installation guide. the main branch is **deprecated** and no work is going to be committed on it anymore (except back-ports)

after that you can dig more using the same provided wiki pages, if you couldn't get it running then I might need more information onboard so that I can actually analyze what's going on. You can communicate information either via our discord server or here in this issue's comments.

**Comment by its-darsh** [comment]
Closing for no response begin provided.

**Comment by clemencyworld1** [comment]
Please where is the installation guide? https://its-darsh.github.io/fabric-wiki/introduction/installation-guide/ leads to nowhere.

**Comment by its-darsh** [comment]
> Please where is the installation guide? https://its-darsh.github.io/fabric-wiki/introduction/installation-guide/ leads to nowhere.

Wrong link, buddy. See readme for proper links.
