### ISSUE TITLE
TypeError on running example from Docs.

### ISSUE THREAD

**Issue by bhaumik-tripathi** [Fabric-Development/fabric#51]
### Discussed in https://github.com/Fabric-Development/fabric/discussions/50

Sum digging into it makes me feel that it is actually a bug, hence the report.
(in `site-packages/fabric/core/service.py`)
The `type` parameter in `__init__` of `Property` class defines itself as of "class type" `T`.
`issubclass` indeed takes an object, but `type` is not guaranteed to always be a class object (it can be `None`)( that's what I think, though I must say I know nothing of how `TypeVar` works.) Any suggestion, corrections and improvements to it are appreciated.

Thanks

**Comment by its-darsh** [comment]
#60 Should fix this.

**Comment by bhaumik-tripathi** [comment]
thanks @its-darsh  :), working now, I can now continue migrating my widgets to fabric. I saw the PR, seems  the issue was the same as I described. I was too nervous and unsure on myself to pull a PR :( :clap:
