### ISSUE TITLE
Fabric not rendering as a layer in Hyprland.

### ISSUE THREAD

**Issue by the-fuckin-nobody** [Fabric-Development/fabric#58]
I know this issue is in the FAQs of the fabric wiki. But none of the solutions work for me.
Here's a screenshot of the issue:
![image](https://github.com/user-attachments/assets/8993dca8-db0b-4f22-8258-946925620f35)

The command used to install fabric:
`pip install git+https://github.com/Fabric-Development/fabric.git`
I event tried to install fabric from AUR, but the issue still persists. I also have tried setting and unsetting the `WAYLAND_DISPLAY` variable to `wayland`.

Please help.

**Comment by its-darsh** [comment]
FYI: The example you're using does not rely on a specific display protocol so that's why it works as a normal window, though, you can try out the bar example instead.

**Comment by the-fuckin-nobody** [comment]
I feel so stupid , even posting about this now lmao. Thanks
